"""Compile src/kernels.cu to PTX with NVRTC and write src/generated/kernels_ptx.h. PTX targets
compute_61 so the driver can JIT it for any GeForce GTX 10 series (Pascal) or newer GPU; it is
the same text for Windows and Linux. On an older GPU the plug-in develops on the CPU.

NVRTC is taken from $SFP_NVRTC_DIR or DaVinci Resolve's Windows install. Without it (macOS,
Linux, build servers) the header kept in the repository is used, provided it was made from the
current kernel source."""
import ctypes, hashlib, os, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESOLVE = Path(os.environ.get('SFP_NVRTC_DIR', r'C:\Program Files\Blackmagic Design\DaVinci Resolve'))
OUT = ROOT / 'src/generated/kernels_ptx.h'


def source():
    src = (ROOT / 'src/kernels.cu').read_text(encoding='utf-8').replace('\r\n', '\n')
    params = (ROOT / 'src/kernel_params.h').read_text(encoding='utf-8').replace('\r\n', '\n')
    return src.replace('#include "kernel_params.h"', params)


def main():
    src = source()
    digest = hashlib.sha256(src.encode()).hexdigest()
    dll = RESOLVE / 'nvrtc64_120_0.dll'
    if not dll.exists():
        if OUT.exists() and f'source sha256 {digest}' in OUT.read_text(encoding='utf-8')[:300]:
            print(f'PTX: NVRTC not installed, using {OUT.relative_to(ROOT)} (matches the kernel source)')
            return
        sys.exit(f'{OUT.relative_to(ROOT)} is missing or older than src/kernels.cu, and NVRTC was not found to rebuild it '
                 '(set SFP_NVRTC_DIR to the folder with nvrtc64_120_0.dll).')
    os.environ['PATH'] = str(RESOLVE) + os.pathsep + os.environ['PATH']
    n = ctypes.CDLL(str(dll))
    prog = ctypes.c_void_p()
    assert n.nvrtcCreateProgram(ctypes.byref(prog), src.encode(), b'kernels.cu', 0, None, None) == 0
    opts = [b'--gpu-architecture=compute_61', b'--use_fast_math', b'-default-device', b'--std=c++14']
    arr = (ctypes.c_char_p * len(opts))(*opts)
    r = n.nvrtcCompileProgram(prog, len(opts), arr)
    size = ctypes.c_size_t()
    n.nvrtcGetProgramLogSize(prog, ctypes.byref(size))
    log = ctypes.create_string_buffer(size.value)
    n.nvrtcGetProgramLog(prog, log)
    if log.value.strip():
        print(log.value.decode(errors='replace'))
    if r != 0:
        sys.exit(f'NVRTC compile failed ({r})')
    n.nvrtcGetPTXSize(prog, ctypes.byref(size))
    ptx = ctypes.create_string_buffer(size.value)
    n.nvrtcGetPTX(prog, ptx)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    data = ptx.value
    body = ','.join(str(b) for b in data + b'\0')
    text = ('// Generated by tools/make_ptx.py from src/kernels.cu\n'
            f'// source sha256 {digest}\n#pragma once\n'
            f'static const unsigned char kKernelsPtx[{len(data) + 1}] = {{{body}}};\n')
    if not OUT.exists() or OUT.read_text(encoding='utf-8') != text:
        OUT.write_bytes(text.encode())
    print(f'PTX {len(data)} bytes -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
