"""Writes src/generated/kernels_msl.h: the kernels' source text (kernel_params.h + kernels.cu) as
Metal Shading Language, which the Mac build compiles on the GPU at run time.

  python tools/make_msl.py            writes the header
  python tools/make_msl.py --check    also compiles the text as C++ with stand-ins for Metal's
                                      keywords and types (needs zig): catches plain mistakes
                                      without a Mac. It is not a Metal compiler.
"""
import subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'src/generated/kernels_msl.h'


def source():
    src = (ROOT / 'src/kernels.cu').read_text(encoding='utf-8').replace('\r\n', '\n')
    params = (ROOT / 'src/kernel_params.h').read_text(encoding='utf-8').replace('\r\n', '\n').replace('#pragma once\n', '')
    assert src.count('#include "kernel_params.h"') == 1
    return '#include <metal_stdlib>\nusing namespace metal;\n' + src.replace('#include "kernel_params.h"', params)


SHIM = r'''
#define __METAL_VERSION__ 1
#include <cmath>
#include <cstddef>
#define device
#define constant
#define thread
#define kernel
struct uint2 { unsigned x, y; };
using std::fabs; using std::fmax; using std::fmin; using std::floor; using std::ceil; using std::pow; using std::sqrt;
using std::exp; using std::log; using std::log2; using std::exp2; using std::sin; using std::cos; using std::tanh;
'''


def check(text):
    sys.path.insert(0, str(ROOT))
    import build
    body = text.replace('#include <metal_stdlib>\nusing namespace metal;\n', SHIM)
    with tempfile.TemporaryDirectory() as tmp:
        f = Path(tmp) / 'kernels_msl_check.cpp'
        f.write_text(body, encoding='utf-8', newline='\n')
        r = subprocess.run([*map(str, build.find_zig()), 'c++', '-target', 'x86_64-linux-gnu', '-std=c++14', '-c', '-o', str(Path(tmp) / 'check.o'), '-Wno-unknown-attributes', '-Wno-unused-function',
                            '-Wall', '-Wextra', '-Wdouble-promotion', str(f)], capture_output=True, text=True)
    print(r.stderr.strip() or 'check: compiles as C++ with Metal stand-ins')
    return r.returncode


def main():
    text = source()
    assert ')SFPMSL"' not in text
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('// Generated by tools/make_msl.py from src/kernel_params.h and src/kernels.cu. Do not edit.\n'
                   '#pragma once\nstatic const char kKernelsMsl[] = R"SFPMSL(' + text + ')SFPMSL";\n', encoding='utf-8', newline='\n')
    print(f'MSL {len(text)} bytes -> {OUT.relative_to(ROOT)}')
    if '--check' in sys.argv:
        sys.exit(check(text))


if __name__ == '__main__':
    main()
