// Chart-fitted colour for the Sigma fp, fp-chart-1 (daylight 2026-09-24; StdA = daylight, Bradford-adapted).
// GENERATED by fp-workspace/arriview/export_ofx.py; regenerate rather than edit.
//
// Fit: ColorChecker 24 in daylight, Color Mode OFF DNGs, white-balanced camera RGB -> XYZ D65,
// CIEDE2000 1.68 in-sample / 1.97 leave-one-out (the as-recorded OFF matrices: 9.63; Sigma's
// calibrated pair: 6.24). One body, FW 5.02. The screen half of the same fit ships in fpSup RAW-View.
//
// Each slot: XYZ under its calibration white -> white-balanced camera RGB (slot . white = 1,1,1).
// The decoder scales each slot's rows by the camera neutral the file's own ColorMatrix gives for that
// white, so white balance and Temp/Tint are unchanged and only the colour is replaced.
// Until a tungsten chart is fitted, the StdA slot is the daylight fit Bradford-adapted to StdA.
#pragma once

namespace sfp {

constexpr const char* kFpChartVersion = "fp-chart-1 (daylight 2026-09-24; StdA = daylight, Bradford-adapted)";

// Calibration whites (xy): CIE Standard Illuminant A, D65.
constexpr double kFpChartWhite[2][2] = {{0.44757, 0.40745}, {0.3127, 0.3290}};

// XYZ (StdA) -> white-balanced camera RGB, row-major.
constexpr double kFpChartStdA[9] = {
    1.311525524, -0.485777848, 0.126780972,
    -0.494185946, 1.299205413, 0.684725882,
    -0.119010925, 0.253303365, 2.465907461
};

// XYZ (D65) -> white-balanced camera RGB, row-major.
constexpr double kFpChartD65[9] = {
    1.517930094, -0.294473588, -0.136128746,
    -0.418346288, 1.158819235, 0.219272553,
    -0.164993867, 0.307162610, 0.780176063
};

// For tests: white-balanced camera RGB -> linear Rec.709 (rows sum to 1), what kFpChartD65 implies.
constexpr double kFpChartTo709[9] = {
    1.899483298, -0.823585198, -0.076080250,
    -0.224448389, 1.683505529, -0.459057140,
    0.045602658, -0.568086023, 1.522700288
};

}  // namespace sfp
